#!/usr/bin/env bash

set -eu

if [ "$EUID" -ne 0 ]
  then echo "Did you use sudo command?"
  exit
fi

echo "Enter adress(example: 127.0.0.1) for the host front-end-challenge: ":

read IP

HOST_NAME="      front-end-challenge"

: ${ETC_HOSTS="/etc/hosts"}

VERBOSE=false

if grep -q "front-end-challenge" "${ETC_HOSTS}";
then
    echo "You already have a host named front-end-challenge"
else
    echo "${IP} ${HOST_NAME}" >> ${ETC_HOSTS}
fi
